version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '02:00'
      timezone: Asia/Shanghai
    open-pull-requests-limit: 10
    groups:
      development-toolchain:
        dependency-type: development
        update-types: [minor, patch]
      production-dependencies:
        dependency-type: production
        update-types: [minor, patch]
    versioning-strategy: increase
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
